server:
  port: 8081

#Database
#spring.jpa.hibernate.ddl-auto=create
spring:
  jpa:
    show-sql: true    
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: GJAVA_060223_BD_CLIENTES
    password: oracle

# Registry Client - Eureka Discovery Client
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8889/eureka